//go:build ignore

/*
 *    Copyright (c) 2018 Unrud <unrud@outlook.com>
 *
 *    This file is part of Remote-Touchpad.
 *
 *    Remote-Touchpad is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    Remote-Touchpad is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with Remote-Touchpad.  If not, see <http://www.gnu.org/licenses/>.
 */

package main

import (
	"bufio"
	"fmt"
	"io"
	"maps"
	"os"
	"regexp"
	"slices"
	"strconv"
)

type Keysym int32

const (
	keysymdefHeader  string = "/usr/include/X11/keysymdef.h"
	output           string = "keysyms.generated.go"
	maxMappedUnicode rune   = 0xff
)

var overrideKeysyms = map[string]rune{
	"XK_BackSpace":   0x08,
	"XK_Tab":         0x09,
	"XK_Linefeed":    0x0a,
	"XK_Clear":       0x0b,
	"XK_Return":      0x0d,
	"XK_Pause":       0x13,
	"XK_Scroll_Lock": 0x14,
	"XK_Sys_Req":     0x15,
	"XK_Escape":      0x1b,
}

func main() {
	headerFile, err := os.Open(keysymdefHeader)
	if err != nil {
		panic(err)
	}
	defer headerFile.Close()
	headerReader := bufio.NewReader(headerFile)
	keysymRe := regexp.MustCompile("^\\#define " +
		"(XK_[a-zA-Z_0-9]+)\\s+" + // keysymName
		"0x([0-9a-f]+)\\s*" + // keysym
		"(?:/\\*\\s*(?:U\\+([0-9A-F]{4,6}))?.*\\*/\\s*)?" + // keysymUnicode (optional)
		"$")
	keysymsMap := make(map[rune]Keysym)
	for {
		line, err := headerReader.ReadString('\n')
		if err == io.EOF {
			if line == "" {
				break
			}
		} else if err != nil {
			panic(err)
		}
		keysymSubmatches := keysymRe.FindStringSubmatch(line)
		if len(keysymSubmatches) == 0 {
			continue
		}
		keysymName := keysymSubmatches[1]
		keysymInt, err := strconv.ParseInt(keysymSubmatches[2], 16, 32)
		keysym := Keysym(keysymInt)
		if err != nil {
			panic(err)
		}
		keysymUnicode, found := overrideKeysyms[keysymName]
		if !found {
			if len(keysymSubmatches[3]) == 0 {
				continue
			}
			keysymUnicodeInt, err := strconv.ParseInt(keysymSubmatches[3], 16, 32)
			keysymUnicode = rune(keysymUnicodeInt)
			if err != nil {
				panic(err)
			}
		}
		if keysymUnicode > maxMappedUnicode {
			continue
		}
		if _, found := keysymsMap[keysymUnicode]; found {
			continue
		}
		keysymsMap[keysymUnicode] = keysym
	}
	content := "// Code generated by keysyms.generator.go. DO NOT EDIT.\n" +
		"//go:build portal || x11\n\n" +
		"package inputcontrol\n\n" +
		"var keysymsMap = map[rune]Keysym{\n"
	for _, unicode := range slices.Sorted(maps.Keys(keysymsMap)) {
		keysym := keysymsMap[unicode]
		content += fmt.Sprintf("\t0x%04x: 0x%08x,\n", unicode, keysym)
	}
	content += "}\n"
	outputFile, err := os.Create(output)
	if err != nil {
		panic(err)
	}
	defer outputFile.Close()
	if _, err := outputFile.WriteString(content); err != nil {
		panic(err)
	}
}
