name: Test
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: stable
      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code
      - name: Go Mod Tidy
        run: go mod tidy && git diff --exit-code

  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - linux
        arch:
          - amd64
        tags:
          - []
          - ['null']
          - [portal]
          - [uinput]
          - [x11]
          - ['null', portal, uinput, x11]
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
      GOFLAGS: -tags=${{ join(matrix.tags, ',') }}
      CGO_ENABLED: '1'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: stable
      - run: sudo apt install libxrandr-dev libxtst-dev libxt-dev
        if: ${{ contains(matrix.tags, 'x11') }}
      - name: Go Vet
        run: go vet ./...
      - name: Go Build
        run: go build ./...
      - name: Go Test
        run: go test -race ./...

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        os:
          - windows
        arch:
          - amd64
        tags:
          - []
          - ['null']
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
      GOFLAGS: -tags=${{ join(matrix.tags, ',') }}
      CGO_ENABLED: '1'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: stable
      - name: Go Vet
        run: go vet ./...
      - name: Go Build
        run: go build ./...
      - name: Go Test
        run: go test -race ./...
